// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKwld1Qz0UO6gNyh6KCphyGKCKogbA_wg',
    appId: '1:338319573985:web:d5d622f555e06c845088a0',
    messagingSenderId: '338319573985',
    projectId: 'managdepartmentdoftware2',
    authDomain: 'managdepartmentdoftware2.firebaseapp.com',
    storageBucket: 'managdepartmentdoftware2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBndrSqxgLbTA38PXmWOgqpeNbBdQrsXRE',
    appId: '1:338319573985:android:86f5902452eeb0d35088a0',
    messagingSenderId: '338319573985',
    projectId: 'managdepartmentdoftware2',
    storageBucket: 'managdepartmentdoftware2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRLRY9h0kqFbD_HfNyJxiCBW5GF3o5ulQ',
    appId: '1:338319573985:ios:a5be18c89c0d06ad5088a0',
    messagingSenderId: '338319573985',
    projectId: 'managdepartmentdoftware2',
    storageBucket: 'managdepartmentdoftware2.firebasestorage.app',
    iosBundleId: 'com.example.managDepartmentSoftware2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRLRY9h0kqFbD_HfNyJxiCBW5GF3o5ulQ',
    appId: '1:338319573985:ios:a5be18c89c0d06ad5088a0',
    messagingSenderId: '338319573985',
    projectId: 'managdepartmentdoftware2',
    storageBucket: 'managdepartmentdoftware2.firebasestorage.app',
    iosBundleId: 'com.example.managDepartmentSoftware2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKwld1Qz0UO6gNyh6KCphyGKCKogbA_wg',
    appId: '1:338319573985:web:373586a1e0c3202d5088a0',
    messagingSenderId: '338319573985',
    projectId: 'managdepartmentdoftware2',
    authDomain: 'managdepartmentdoftware2.firebaseapp.com',
    storageBucket: 'managdepartmentdoftware2.firebasestorage.app',
  );
}
